PREFIX : <http://dbpedia.org/resource/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT DISTINCT ?s ?country STR(?cityname) ?lat ?long
WHERE {
    ?s a dbo:City .
    ?s rdfs:label ?cityname .
    FILTER(LANG(?cityname) = "en") .
    ?s dbo:country ?country .
    ?s geo:lat ?lat .
    ?s geo:long ?long .
    FILTER(?lat > 48.5 && ?lat < 49.5) .
}
ORDER BY ?country
LIMIT 300
